Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Gateway-Service, pull requests merged in 2024-09, with the labels that each got.

#3 Se añadio descripciones en swagger y se aplicó formato
  src/persons/persons.controller.ts
Labels: documentation

#4 Adición Modulo de Documentos y Rutas Especificas
  src/app.module.ts
  src/procedure-documents/procedure-documents.controller.ts
  src/procedure-documents/procedure-documents.module.ts
Labels: new

#6 Filtros de búsqueda de persona
  src/persons/dto/filter-person.dto.ts
  src/persons/persons.controller.ts
Labels: enhancement

#8 Agrupacion de archivos - modulo en "General"
  src/app.module.ts
  src/general/procedure-documents/procedure-documents.controller.ts
  src/general/procedure-documents/procedure-documents.module.ts
Labels: enhancement
