Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Gateway-Service, pull requests merged in 2024-10, with the labels that each got.

#10 Creación del modulo de affiliate
  src/affiliates/affiliates.controller.ts
  src/affiliates/affiliates.module.ts
  src/app.module.ts
Labels: enhancement

#12 End Point HTTP en gateway para sacar los documentos de un afiliado
  src/affiliates/affiliates.controller.ts
Labels: new

#14 End Ponit, para Enlazar y subir doucumento del afiliado Documentada
  src/affiliates/affiliates.controller.ts
  src/affiliates/pipes/file-required.pipe.ts
Labels: new

#16 Endpoint de API para desplegar la información del afiliado con su rel…
  src/persons/persons.controller.ts
Labels: enhancement

#17 End Ponit, para Enlazar y subir doucumento del afiliado Documentada
  package.json
  src/affiliates/affiliates.controller.ts
  src/affiliates/pipes/file-required.pipe.ts
  src/app.module.ts
  src/general/categories.controller.ts
  src/general/cities.controller.ts
  src/general/degrees.controller.ts
  src/general/financial-entities.controller.ts
  src/general/general.module.ts
  src/general/index.ts
  src/general/kinships.controller.ts
  src/general/pension-entities.controller.ts
  src/general/procedure-documents.controller.ts
  src/general/procedure-documents/procedure-documents.module.ts
  src/general/units.controller.ts
Labels: new

#19 Ajuste de nombre de funcion bug
  src/general/degrees.controller.ts
  src/general/units.controller.ts
Labels: bug

#20 Refactorización y añadido de formato en código
  .prettierrc
  src/auth/auth.controller.ts
  src/auth/decorators/index.ts
  src/auth/decorators/token.decorator.ts
  src/auth/decorators/user.decorator.ts
  src/auth/dto/login-user.dto.ts
  src/auth/guards/auth.guard.ts
  src/main.ts
  src/persons/dto/create-person.dto.ts
  src/persons/persons.controller.ts
  src/persons/persons.module.ts
  src/transports/nats.module.ts
  yarn.lock
Labels: new

#22 Api Http para encontrar un documento especifico del afiliado
  src/affiliates/affiliates.controller.ts
Labels: new

#23 Endpoint para mostrar al afiliado relacionado a una persona
  src/persons/persons.controller.ts
Labels: enhancement

#25 Api para mostrar datos del afiliados y ajuste de formato
  src/affiliates/affiliates.controller.ts
Labels: new

#26 ajuste de nombre de api
  src/affiliates/affiliates.controller.ts
Labels: enhancement

#29 APIs para mostrar datos de los modulos, tipos, y modalidades
  src/general/general.module.ts
  src/general/index.ts
  src/general/modules.controller.ts
Labels: enhancement, new

#30 ajuste para descarga automatica del documento pdf
  src/affiliates/affiliates.controller.ts
Labels: enhancement

#32 Creación de registro de huellas
  src/persons/dto/create-person-fingerprint.dto.ts
  src/persons/dto/filter-person.dto.ts
  src/persons/dto/index.ts
  src/persons/persons.controller.ts
Labels: enhancement

#34 Api http para cotejar los documentos del afiliado con los del tramite…
  src/affiliates/affiliates.controller.ts
  src/general/categories.controller.ts
  src/general/cities.controller.ts
  src/general/degrees.controller.ts
  src/general/financial-entities.controller.ts
  src/general/general.module.ts
  src/general/index.ts
  src/general/kinships.controller.ts
  src/general/modules.controller.ts
  src/general/pension-entities.controller.ts
  src/general/procedure-documents.controller.ts
  src/general/units.controller.ts
Labels: new

#37 Refactorización DTO para registar huellas de personas recibiendo un a…
  src/persons/dto/create-person-fingerprint.dto.ts
Labels: enhancement

#38 Documentación de API para crear huellas
  src/persons/dto/create-person-fingerprint.dto.ts
  src/persons/persons.controller.ts
Labels: documentation

#39 Endpoint para ver el listado de las huellas digitales
  src/persons/persons.controller.ts
Labels: enhancement
