Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Gateway-Service, pull requests merged in 2025-01, with the labels that each got.

#76 Validación para subidad de archivos solo pdf
  src/affiliates/affiliates.controller.ts
  src/common/pipes/file-required.pipe.ts
Labels: enhancement

#77 Añadido timestamp en records e ignorar usuario pvtbe al iniciar sesion
  src/auth/auth.controller.ts
  src/database/migrations/1738092745014-add_createAt_records.ts
Labels: bug

#79 api para analizar e importar documentos del afiliado
  src/affiliates/affiliates.controller.ts
Labels: new
